override pkg = bun-plugin-solid
include ../../shared/deps.mk
include ../../shared/lint.mk
include ../../shared/typescript.mk

# Note: This is a plugin for Bun, which can read typescript directly, no need to build anything.